### ISSUE TITLE
OPENSSL_internal:NO_SHARED_CIPHER with TLSv1.2

### ISSUE THREAD

**Issue by abkura** [line/armeria#2403]
What does TLS handshake failed:","javax.net.ssl.SSLHandshakeException: error:100000b8:SSL routines:OPENSSL_internal:NO_SHARED_CIPHER"  exception really mean?

**Comment by trustin** [comment]
Hi! It means there are no common cipher suites between the client and the server, which usually means one of them has an old or misconfigured SSL/TLS setup. HTTP/2 requires both clients and servers support a minimum set of cipher suites. Please make sure to enable those cipher suites.

**Comment by trustin** [comment]
Oh, and please let us know if both client and server are Armeria.

**Comment by abkura** [comment]
Thanks @trustin for your answer. I'm trying to configure HTTPS for Zipkin Server which uses Armeria.

Below is the configuration:

```
server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLS
    ciphers: "AES256-SHA256, AES128-SHA256, AES256-GCM-SHA384, AES128-GCM-SHA256, ECDHE-RSA-AES256-SHA384, ECDHE-RSA-AES128-SHA256"
    key-store-type: JKS
    key-store: file:/usr/zipkin/keystore.jks
    key-password: changeit
  use-forward-headers: true
  compression:
    enabled: true
    # compresses any response over min-response-size (default is 2KiB)
    # Includes dynamic json content and large static assets from zipkin-ui
    mime-types: application/json,application/javascript,text/css,image/svg
    min-response-size: 2048
armeria:
  ports:
    - port: 8443
      protocols:
        - https
  ssl:
    enabled: true
    ciphers: "AES256-SHA256, AES128-SHA256, AES256-GCM-SHA384, AES128-GCM-SHA256, ECDHE-RSA-AES256-SHA384, ECDHE-RSA-AES128-SHA256"
    enabled-protocols: "TLSv1.2"
    key-store-type: JKS
    key-store: file:/usr/zipkin/keystore.jks
    key-password: changeit
  compression:
    enabled: ${server.compression.enabled}
    mime-types: ${server.compression.mime-types}
    min-response-size: ${server.compression.min-response-size}
  gracefulShutdownQuietPeriodMillis: -1
  gracefulShutdownTimeoutMillis: -1
```
Seeing any of the below error message however i keep the configuration 

1)  TLS handshake failed:javax.net.ssl.SSLHandshakeException: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN

2)TLS handshake failed:","javax.net.ssl.SSLHandshakeException: error:100000b8:SSL routines:OPENSSL_internal:NO_SHARED_CIPHER" 

3)Caused by: java.lang.IllegalStateException: SSLContext has no cipher suites enabled.

I would really appreciate if you can provide any simple configuration to make this work
