### ISSUE TITLE
Change distribution summary config with YAML [Spring Integration]

### ISSUE THREAD

**Issue by okue** [line/armeria#3309]
It would be good if we can change this distribution summary config with YAML like
```yaml
management:
  metrics:
    distribution:
      percentiles:
        - 0.5
        - 0.75
        - 0.9
        - 0.95
        - 0.99
```

https://armeria.dev/docs/advanced-metrics#changing-the-default-distribution-summary-config

**Comment by eisig** [comment]
Maybe add support in spring auto configuration ?

**Comment by eisig** [comment]
Sorry not notice the title already say “Spring Integration”😅

**Comment by okue** [comment]
Yes, I want `armeria-spring-boot-starter` to support this kind of feature.

**Comment by eisig** [comment]
@okue do your woking on it? If not, I may have a try.

**Comment by okue** [comment]
@eisig i do nothing yet. Thank you!

**Comment by ta7uw** [comment]
I think the above distribution summary can be applied by setting as the following
What do you think? @okue 

```yaml
management:
  metrics:
    distribution:
      percentiles:
        armeria.server: 0.5, 0.75, 0.9, 0.95, 0.99
```
