### ISSUE TITLE
Add `exclude` option to `internal-services` in Spring integration

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5753]
`internal-service` provides `include` options to opt in services to serve only in the non-service port. But `exclude` isn't supported to opt out of `include`. `exclude` option will be useful for less sensitive internal services. For example, in the case of the health check service, there will be a need to provide both the service port and the internal port because sensible information is not exposed by `HealthCheckService` if updating the status isn't supported by the client.
```yaml
armeria:
  ports:
    - port: 8080
      protocol: HTTP
  health-check-path: /...
  internal-services:
    exclude: HEALTH
    port: 9090
```

In addition to `exclude`, multiple internal service configurations would be helpful to respond to complex situations.

```yaml
armeria:
  ports:
    - port: 8080
      protocol: HTTP
  internal-services:
    - include: DOCS
      port: 9090
    - include: HEALTH
      port: 9091
    ...
```
